### ISSUE TITLE
Failed to activate the eslint package

### ISSUE THREAD

**Issue by wojtekgalaj** [iancmyers/atom-eslint#20]
[Enter steps to reproduce below:]
1. Install "eslint" package from the atom package manager

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10
**Thrown From**: [eslint](https://github.com/iancmyers/atom-eslint) package, v0.15.0
### Stack Trace

Failed to activate the eslint package

```
At Cannot read property 'rules' of undefined

TypeError: Cannot read property 'rules' of undefined
  at Object.module.exports.loadConfig (/Users/wojciech/.atom/packages/eslint/lib/eslint.coffee:38:61)
  at Object.module.exports.activate (/Users/wojciech/.atom/packages/eslint/lib/eslint.coffee:11:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -0:36.1 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  2x -0:34.2 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
eslint, v0.15.0
vim-mode, v0.38.0

# Dev
No dev packages
```

**Comment by phoncu** [comment]
eslint v0.21.2 same problem
