### ISSUE TITLE
Uncaught Error: Definition for rule 'no-extra-bind' was not found.

### ISSUE THREAD

**Issue by elliotboney** [iancmyers/atom-eslint#22]
[Enter steps to reproduce below:]
1. Just saving a document with eslint is giving me this.

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.3
**Thrown From**: [eslint](https://github.com/iancmyers/atom-eslint) package, v0.15.0
### Stack Trace

Uncaught Error: Definition for rule 'no-extra-bind' was not found.

```
At /Applications/Atom.app/Contents/Resources/app/src/pane.js:794

Error: Definition for rule 'no-extra-bind' was not found.
  at /Users/eboney/DotFiles/misc/atom.symlink/packages/eslint/node_modules/eslint/lib/eslint.js:323:27
  at Array.forEach (native)
  at EventEmitter.module.exports.api.verify (/Users/eboney/DotFiles/misc/atom.symlink/packages/eslint/node_modules/eslint/lib/eslint.js:297:16)
  at ESLintGutterView.module.exports.ESLintGutterView.lint (/Users/eboney/DotFiles/misc/atom.symlink/packages/eslint/lib/eslint-gutter-view.coffee:40:24)
  at /Users/eboney/DotFiles/misc/atom.symlink/packages/eslint/lib/eslint-gutter-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:977:19)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:628:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:554:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:537:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:687:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```
### Commands

```
     -1:52.8 core:backspace (atom-text-editor.editor.source-js.is-focused)
     -1:50.9 core:delete (atom-text-editor.editor.source-js.is-focused)
     -1:50.1 core:save (atom-text-editor.editor.source-js.is-focused)
     -1:33.1 cut-line:cut-line (atom-text-editor.editor.source-js.is-focused)
     -1:32.3 core:save (atom-text-editor.editor.source-js.is-focused)
     -1:28.4 core:undo (atom-text-editor.editor.source-js.is-focused)
     -1:27.6 core:save (atom-text-editor.editor.source-js.is-focused)
     -1:24.8 editor:consolidate-selections (atom-text-editor.editor.source-js.is-focused)
     -1:24.8 core:cancel (atom-text-editor.editor.source-js.is-focused)
     -1:13.5 core:confirm (atom-text-editor.editor.mini)
     -0:47.7 core:save (input#linter-eslint.disableWhenNoEslintrcFileInPath)
     -0:38.5 core:select-all (atom-text-editor.editor.mini)
     -0:37.7 core:confirm (atom-text-editor.editor.mini)
  2x -0:12.7 linter:lint (atom-text-editor.editor.source-js.is-focused)
  6x -0:06.7 linter:next-message (atom-text-editor.editor.source-js.is-focused)
     -0:01.4 core:save (atom-text-editor.editor.source-js.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      ".idea"
    ],
    "disabledPackages": [
      "autocomplete-snippets",
      "script",
      "atom-jsfmt",
      "background-tips",
      "atom-color-highlight",
      "react",
      "Tern",
      "deprecation-cop",
      "linter-csslint",
      "eslint"
    ],
    "themes": [
      "spacegray-dark-ui",
      "spacegray-dark-syntax"
    ],
    "projectHome": "/Users/eboney/Code",
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.23.1
atom-ternjs, v0.5.8
auto-update-packages, v0.2.2
autocomplete-plus, v2.7.0
color-picker, v1.5.0
cut-line, v0.10.0
docblockr, v0.6.3
editor-grammar-scope, v0.1.0
highlight-line, v0.10.1
jsformat, v0.7.18
language-applescript, v0.1.0
language-javascript-semantic, v0.1.0
language-liquid, v0.2.0
language-viml, v0.2.0
less-autocompile, v1.0.0
linter, v0.12.0
linter-eslint, v0.5.0
minimap, v4.6.0
pretty-json, v0.3.2
remember-session, v0.5.1
set-syntax, v0.2.1
spacegray-dark-syntax, v0.2.0
spacegray-dark-ui, v0.8.0
syntax-settings, v0.7.1
wakatime, v4.0.1

# Dev
No dev packages
```

**Comment by elliotboney** [comment]
I fixed this by going into the package directory and manually running "npm install babel-eslint"
